// No React/Next or image imports here — the MCP server imports this too.
export interface BlogMeta {
  id: number
  slug: string
  title: string
  description: string
  date: string
  hidden: boolean
  tags: string[]
  file: string // MDX basename in ./markdown
}

const BLOG_METADATA: BlogMeta[] = [
  {
    id: 32,
    slug: 'docker-restart-always-start-limit',
    title: 'Home Lab: Self-Healing a Docker Boot Race',
    description:
      'Why my Docker daemon stayed dead after a slow-wifi boot, and the two-layer IaC fix that recovers it',
    date: '2026-07-17',
    hidden: false,
    tags: [
      'home-lab',
      'self-hosted',
      'docker',
      'systemd',
      'ansible',
      'linux',
      'networking',
      'wifi',
      'watchdog',
      'discord',
      'observability',
      'iac',
      'sre',
      'devops',
    ],
    file: 'building-my-home-server-p13',
  },
  {
    id: 31,
    slug: 'irsa-without-eks-self-hosted-oidc',
    title: 'Dev Platform: Teaching AWS to Trust My Cluster',
    description:
      'Milestone 2, part one: IRSA, OIDC from first principles, and hosting my own OpenID provider on S3',
    date: '2026-06-27',
    hidden: false,
    tags: [
      'dev-platform',
      'kubernetes',
      'irsa',
      'oidc',
      'aws',
      'iam',
      'sts',
      'talos',
      's3',
      'terraform',
      'gitops',
      'devops',
      'self-hosted',
    ],
    file: 'self-hosted-developer-platform-on-k8s-p3',
  },
  {
    id: 30,
    slug: 'ai-alert-triage-prometheus-loki',
    title: 'Home Lab: An AI Agent That Triages My Alerts',
    description:
      'Letting Claude investigate firing alerts and post the root-cause hypothesis to Discord',
    date: '2026-06-14',
    hidden: false,
    tags: [
      'home-lab',
      'self-hosted',
      'ai',
      'claude',
      'mcp',
      'observability',
      'prometheus',
      'loki',
      'alertmanager',
      'grafana',
      'docker',
      'fastapi',
      'python',
      'sre',
      'devops',
    ],
    file: 'building-my-home-server-p12',
  },
  {
    id: 29,
    slug: 'cilium-ebpf-on-talos',
    title: 'Dev Platform: Guardrails, then Trading Flannel for eBPF',
    description:
      'Milestones 0 and 1: SOPS-encrypted secrets, CI gates, and swapping the CNI for Cilium on Talos',
    date: '2026-05-31',
    hidden: false,
    tags: [
      'dev-platform',
      'kubernetes',
      'cilium',
      'ebpf',
      'talos',
      'sops',
      'age',
      'github-actions',
      'kubeconform',
      'kyverno',
      'helm',
      'terraform',
      'gitops',
      'devops',
      'self-hosted',
    ],
    file: 'self-hosted-developer-platform-on-k8s-p2',
  },
  {
    id: 28,
    slug: 'terraform-oidc-aws-vercel-github-actions',
    title: 'Consolidating Lambda Infrastructure',
    description:
      'Bringing the contact Lambda, layers, and Terraform into one repo with end-to-end OIDC',
    date: '2026-05-28',
    hidden: false,
    tags: [
      'aws',
      'terraform',
      'hcp-terraform',
      'lambda',
      'iam',
      'oidc',
      'cloudflare',
      'vercel',
      'ses',
      'ssm',
      's3',
      'github-actions',
      'nextjs',
      'devops',
    ],
    file: 'consolidating-lambda-infrastructure',
  },
  {
    id: 27,
    slug: 'vaultwarden-self-hosted-aws-failover',
    title: 'Home Lab: Vaultwarden & Disaster Recovery',
    description:
      'Self-hosting a password manager with automated backups to AWS',
    date: '2026-05-25',
    hidden: false,
    tags: [
      'linux',
      'home-lab',
      'self-hosted',
      'vaultwarden',
      'docker',
      'ansible',
      'aws',
      'terraform',
      'cloudwatch',
      'lambda',
      'ec2',
      's3',
      'tailscale',
      'disaster-recovery',
      'nginx',
    ],
    file: 'building-my-home-server-p11',
  },
  {
    id: 26,
    slug: 'talos-kubernetes-on-aws-terraform',
    title: 'Dev Platform: Bootstrapping Talos on AWS',
    description:
      'Provisioning Kubernetes on Talos Linux with Terraform and EC2',
    date: '2026-05-22',
    hidden: false,
    tags: [
      'dev-platform',
      'talos',
      'kubernetes',
      'aws',
      'terraform',
      'ec2',
      'networking',
      'grpc',
      'devops',
      'debugging',
      'self-hosted',
    ],
    file: 'self-hosted-developer-platform-on-k8s-p1',
  },
  {
    id: 25,
    slug: 'tmux-pane-layouts-yaml',
    title: 'tmux-pane-controller',
    description: 'Declarative pane layouts for tmux',
    date: '2026-04-24',
    hidden: false,
    tags: ['tmux', 'bash', 'cli', 'productivity'],
    file: 'tmux-pane-controller',
  },
  {
    id: 24,
    slug: 'netalertx-network-scanning-docker',
    title: 'Home Lab: Network Scanning with NetAlertX',
    description:
      'Detecting devices and monitoring ARP traffic on the local network',
    date: '2026-04-17',
    hidden: false,
    tags: [
      'linux',
      'home-lab',
      'self-hosted',
      'netalertx',
      'docker',
      'networking',
      'arp',
      'nginx',
      'ansible',
    ],
    file: 'building-my-home-server-p10',
  },
  {
    id: 23,
    slug: 'ups-monitoring-without-usb-prometheus',
    title: 'Home Lab: UPS Monitoring & Failover',
    description: 'Automated shutdown on power loss with Prometheus alerting',
    date: '2026-04-10',
    hidden: false,
    tags: [
      'linux',
      'home-lab',
      'self-hosted',
      'ups',
      'bash',
      'prometheus',
      'grafana',
      'monitoring',
      'ansible',
      'cron',
    ],
    file: 'building-my-home-server-p9',
  },
  {
    id: 22,
    slug: 'tailscale-pihole-samba-subnet-routing',
    title: 'Home Lab: Remote Access with Tailscale',
    description:
      'Secure WireGuard-based VPN with Pi-hole DNS and Samba over the mesh',
    date: '2026-04-03',
    hidden: false,
    tags: [
      'linux',
      'home-lab',
      'self-hosted',
      'tailscale',
      'wireguard',
      'vpn',
      'pi-hole',
      'dns',
      'samba',
      'ufw',
      'ansible',
    ],
    file: 'building-my-home-server-p8',
  },
  {
    id: 21,
    slug: 'tmux-git-worktree-plugin',
    title: 'tmux-worktree',
    description: 'A tmux plugin for managing git worktrees in the age of AI',
    date: '2026-03-27',
    hidden: false,
    tags: [
      'tmux',
      'git',
      'worktrees',
      'neovim',
      'bash',
      'cli',
      'ai',
      'productivity',
    ],
    file: 'tmux-worktree',
  },
  {
    id: 20,
    slug: 'mcp-server-ai-chat-widget-nextjs',
    title: 'Building an AI Chat Widget with MCP',
    description: 'Adding an AI-powered assistant to my portfolio',
    date: '2026-03-18',
    hidden: false,
    tags: ['mcp', 'ai', 'claude', 'typescript', 'nextjs', 'react', 'sse'],
    file: 'mcp-server-and-chat-widget',
  },
  {
    id: 19,
    slug: 'lambda-deployment-pipeline-testing',
    title: 'Lambda Deployments v2',
    description:
      'Taking the Lambda deployment pipeline from MVP to production-ready',
    date: '2026-03-16',
    hidden: false,
    tags: [
      'aws',
      'lambda',
      'cicd',
      'github-actions',
      'testing',
      'vitest',
      'pytest',
      'shellcheck',
    ],
    file: 'lambda-deployments-v2',
  },
  {
    id: 18,
    slug: 'jellyfin-docker-nginx-reverse-proxy',
    title: 'Home Lab: Media Streaming with Jellyfin',
    description: 'Self-hosted media server with Docker and Nginx reverse proxy',
    date: '2026-03-13',
    hidden: false,
    tags: [
      'linux',
      'docker',
      'containers',
      'home-lab',
      'self-hosted',
      'jellyfin',
      'nginx',
      'ansible',
    ],
    file: 'building-my-home-server-p7',
  },
  {
    id: 17,
    slug: 'vcs-remote-sync-s3-sqlite',
    title: 'Nexio: Remote State Management with S3',
    description: 'Taking Nexio from Local-Only to Collaborative',
    date: '2026-03-09',
    hidden: false,
    tags: ['golang', 'vcs', 'nexio', 'aws', 's3', 'sqlite'],
    file: 'remote-state-management',
  },
  {
    id: 16,
    slug: 'loki-promtail-docker-logs-grafana',
    title: 'Home Lab: Centralized Logging with Loki',
    description:
      'Aggregating container and system logs with Promtail and Grafana',
    date: '2026-03-07',
    hidden: false,
    tags: [
      'linux',
      'docker',
      'containers',
      'home-lab',
      'self-hosted',
      'grafana',
      'loki',
      'promtail',
      'logging',
      'monitoring',
      'nginx',
    ],
    file: 'building-my-home-server-p6',
  },
  {
    id: 15,
    slug: 'pihole-docker-local-dns',
    title: 'Home Lab: Ad Blocking with Pi-hole',
    description:
      'Network-wide DNS filtering with Docker and custom firewall rules',
    date: '2026-03-02',
    hidden: false,
    tags: [
      'linux',
      'ubuntu',
      'docker',
      'ufw',
      'nginx',
      'containers',
      'home-lab',
      'self-hosted',
      'pi-hole',
      'dns',
      'ansible',
    ],
    file: 'building-my-home-server-p5',
  },
  {
    id: 14,
    slug: 'json-to-sqlite-2000x-faster',
    title: 'Nexio: From JSON Files to SQLite',
    description:
      "How a Simple Benchmark Convinced Me to Rewrite Nexio's Storage Layer",
    date: '2026-02-28',
    hidden: false,
    tags: ['sqlite', 'golang', 'vcs', 'nexio', 'performance', 'optimization'],
    file: 'from-json-to-sqlite',
  },
  {
    id: 13,
    slug: 'cloudgoat-data-secrets-imds-privesc',
    title: 'CloudGoat: Data Secrets',
    description:
      'Write-up: Exploiting EC2 User Data and IMDS to escalate privileges',
    date: '2026-02-19',
    hidden: false,
    tags: [
      'hacking',
      'write-up',
      'cloudgoat',
      'aws',
      'pacu',
      'ec2',
      'lambda',
      'secrets-manager',
      'iam',
      'exploit',
      'vulnerability',
    ],
    file: 'cloudgoat__data-secrets',
  },
  {
    id: 12,
    slug: 'cloudgoat-sns-secrets-api-key-leak',
    title: 'CloudGoat: SNS Secrets',
    description: 'Write-up: Exploiting SNS subscriptions to leak API keys',
    date: '2026-01-17',
    hidden: false,
    tags: [
      'hacking',
      'write-up',
      'cloudgoat',
      'aws',
      'pacu',
      'awscli',
      'sns',
      'api-gw',
      'iam',
      'exploit',
      'vulnerability',
    ],
    file: 'cloudgoat__sns-secrets',
  },
  {
    id: 10,
    slug: 'cloudgoat-beanstalk-secrets',
    title: 'CloudGoat: Beanstalk Secrets',
    description:
      'Write-up: low-privilege user to admin via secrets in Beanstalk env vars and iam:CreateAccessKey — with the AWS CLI and Pacu',
    date: '2026-01-11',
    hidden: false,
    tags: [
      'hacking',
      'write-up',
      'cloudgoat',
      'aws',
      'awscli',
      'pacu',
      'beanstalk',
      'iam',
      'privesc',
      'exploit',
      'vulnerability',
    ],
    file: 'cloudgoat__beanstalk-secrets',
  },
  {
    id: 9,
    slug: 'content-addressable-storage-blake3',
    title: 'Nexio: Storage Optimization',
    description: 'Transforming Nexio with Content-Addressable Storage',
    date: '2025-12-21',
    hidden: false,
    tags: [
      'blake3',
      'git',
      'golang',
      'vcs',
      'nexio',
      'performance',
      'optimization',
    ],
    file: 'blob-storage-optimization',
  },
  {
    id: 8,
    slug: 'build-your-own-git-in-go',
    title: 'Nexio: Developing My Own VCS',
    description: 'Learning Git the Hard Way',
    date: '2025-11-13',
    hidden: false,
    tags: ['git', 'golang', 'vcs', 'nexio'],
    file: 'developing-my-own-vcs',
  },
  {
    id: 7,
    slug: 'docker-bypasses-ufw-firewall',
    title: 'Home Lab: Docker, UFW & Nginx',
    description: 'Containerized services with firewall rules and reverse proxy',
    date: '2025-10-26',
    hidden: false,
    tags: [
      'linux',
      'ubuntu',
      'docker',
      'ufw',
      'nginx',
      'containers',
      'home-lab',
      'self-hosted',
    ],
    file: 'building-my-home-server-p4',
  },
  {
    id: 6,
    slug: 'linux-disk-partitioning-rsync-backups',
    title: 'Home Lab: Volumes & Backups',
    description: 'Disk partitioning, mounting, and automated rsync backups',
    date: '2025-10-11',
    hidden: false,
    tags: [
      'linux',
      'ubuntu',
      'fdisk',
      'cron',
      'home-lab',
      'self-hosted',
      'rsync',
    ],
    file: 'building-my-home-server-p3',
  },
  {
    id: 5,
    slug: 'samba-smb-share-ubuntu',
    title: 'Home Lab: File Sharing with Samba',
    description: 'Setting up SMB shares for local network access',
    date: '2025-10-03',
    hidden: false,
    tags: ['linux', 'ubuntu', 'smb', 'samba', 'home-lab', 'self-hosted'],
    file: 'building-my-home-server-p2',
  },
  {
    id: 4,
    slug: 'ubuntu-server-ssh-hardening',
    title: 'Home Lab: Initial Setup & SSH',
    description:
      'Ubuntu install, networking with Netplan, and hardened SSH access',
    date: '2025-10-03',
    hidden: false,
    tags: [
      'linux',
      'ubuntu',
      'ssh',
      'wifi',
      'netplan',
      'home-lab',
      'self-hosted',
      'security',
      'ufw',
    ],
    file: 'building-my-home-server-p1',
  },
  {
    id: 3,
    slug: 'lambda-deployments-github-actions-oidc',
    title: 'Lambda Deployments',
    description:
      'Automating AWS Lambda and Layer Deployments with GitHub Actions',
    date: '2025-10-19',
    hidden: false,
    tags: ['aws', 'lambda', 'cicd', 'github-actions', 'terraform', 'oidc'],
    file: 'lambda-deployments',
  },
  {
    id: 2,
    slug: 'ibm-tech-2024-conference',
    title: 'IBM Tech 2024 Conference',
    description: 'Insights and takeaways from the IBM Tech 2024 conference.',
    date: '2024-03-22',
    hidden: true,
    tags: ['ibm', 'red-hat', 'openshift', 'ansible', 'security', 'watsonx'],
    file: 'ibm-tech-2024-conference',
  },
  {
    id: 1,
    slug: 'travis-ci-to-tekton-migration',
    title: 'Migrating to Tekton',
    description:
      'This blog post is about my experience migrating from Travis CI to Tekton.',
    date: '2023-12-13',
    hidden: true,
    tags: [
      'cicd',
      'tekton',
      'ruby-on-rails',
      'travis-ci',
      'kubernetes',
      'docker',
    ],
    file: 'migrating-to-tekton',
  },
]

export default BLOG_METADATA
